### ISSUE TITLE
 check-manifest integration / merge

### ISSUE THREAD

**Issue by regebro** [regebro/pyroma#1]
Hi,
There is another tool which may overlap with Pyroma. Merging them together might be useful for the users: https://github.com/mgedmin/check-manifest
-- Anonymous

**Comment by regebro** [comment]
Yes, you are right that it overlaps somewhat. I use both, especially through zest.releaser, which has hooks. So if both are installed, both will be run before release.
You are right that the tools probably could be merged. I'll discuss that with @mgedmin at some point in the future.

**Comment by mgedmin** [comment]
I'm open to providing an API (or adding a hook) in check-manifest to make it possible to integrate it with pyroma.

**Comment by regebro** [comment]
Yeah, that seems reasonable. It would be run twice from zest.releaser, though, but I think check-manifest is run first anyway, so you'd only notice if it actually warns.

**Comment by mgedmin** [comment]
I'm sure we can find a way not to do the same check twice (worst case I can keep track of which hooks have been called in a module global, as it's all being done in process in zest.releaser).

**Comment by regebro** [comment]
Maybe cache the result and just return it instead of printing it? 
Pyroma will need to know if it failed or succeeded, but that way we don't need to analyse the file twice, nor print the errors twice.
