### ISSUE TITLE
Pyroma installation fails if LC_ALL is set to en_US.ascii

### ISSUE THREAD

**Issue by ericof** [regebro/pyroma#12]
Error:
`Downloading pyroma-2.3.tar.gz (345kB)", " Complete output from command python setup.py egg_info:", " Traceback (most recent call last):", " File \"<string>\", line 1, in <module>", " File \"/tmp/pip-build-79vf1ldo/pyroma/setup.py\", line 8, in <module>", " long_description=open(\"README.rst\", 'rt').read() + \"\\n\" +", " File \"/srv/pyramid/kjvrvg/venv/lib/python3.5/encodings/ascii.py\", line 26, in decode", " return codecs.ascii_decode(input, self.errors)[0]", " UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3516: ordinal not in range(128)", " ", " ----------------------------------------"], "warnings": []}`

That was introduced in the version 2.3 release.

**Comment by rhoerbe** [comment]
would you mind to publish an update version to pypi? Setting LANG to en.UTF-8 does not resolve the problem, but installing pyroma==2.4dev0 does.

**Comment by regebro** [comment]
2.3.1 Released

**Comment by jabdoa2** [comment]
Awesome! Thanks!
