### ISSUE TITLE
[Question] Continuous integration behavior

### ISSUE THREAD

**Issue by Kristinita** [regebro/pyroma#16]
### 1. Summary

My pyroma Final rating:

1. Local — 10/10,
1. Travis CI — 9/10,
1. AppVeyor — 0/10,
1. CircleCI — 0/10.

### 2. Local environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.4,
+ pyroma 2.3.

### 3. Configuration

See my `Readme.rst`, `requirements.txt`, `setup.cfg`, `setup.py`, `.travis.yml`, `appveyor.yml` and `circle.yml` in [**test repository**](https://github.com/Kristinita/SashaPyromaDebugging).

I add [**flake8**](https://pypi.python.org/pypi/flake8), [**pydocstyle**](http://www.pydocstyle.org/) and [**vulture**](https://github.com/jendrikseipp/vulture) in CI `yml` files, to demonstrate, that another tools correct works for me in Continuous Integration.

### 4. Steps to reproduce

In root folder of my repository I run:

    pyroma .

### 5. Expected behavior

Local:

```
D:\SashaPyromaDebugging>pyroma .
------------------------------
Checking .
Registered VCS backend: git
Registered VCS backend: hg
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect

Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect

Registered VCS backend: svn
Registered VCS backend: bzr
Found erichek
------------------------------
Final rating: 10/10
Your cheese is so fresh most people think it's a cream: Masc
```

### 6. CI behavior

+ [**Travis CI**](https://travis-ci.org/Kristinita/SashaPyromaDebugging/builds/336832977),
+ [**AppVeyor**](https://ci.appveyor.com/project/Kristinita/sashapyromadebugging/build/1.0.1),
+ [**CircleCI**](https://circleci.com/gh/Kristinita/SashaPyromaDebugging/1).

Thanks.

**Comment by The-Compiler** [comment]
Maybe try upgrading to a newer `setuptools` via `pip install -U setuptools`?

**Comment by Kristinita** [comment]
@The-Compiler , thanks, it works!

Have you any ideas, why on Linux CI ([**Travis**](https://travis-ci.org/Kristinita/SashaPyromaDebugging/jobs/336898980#L512) and [**Circle**](https://circleci.com/gh/Kristinita/SashaPyromaDebugging/3)) I get:

    The package's long_description is quite short.

But in [**AppVeyor**](https://ci.appveyor.com/project/Kristinita/sashapyromadebugging/build/1.0.2#L66) — Windows CI — I get 10/10?

Thanks.

**Comment by The-Compiler** [comment]
Note that pyroma itself doesn't need a newer setuptools - it's your own `setup.py` most likely (with lots of stuff in `setup.cfg`).

As for the `long_description`: Your `setup.cfg` says `file: README.RST` but the file is called `Readme.rst`. Windows is case-insensitive, but Linux isn't.

**Comment by regebro** [comment]
Your setup.py calls pip.req.parse_requirements(), which is discouraged use of pip internals, and which no longer works.

**Comment by regebro** [comment]
This seems to be working now.
