### ISSUE TITLE
More checks

### ISSUE THREAD

**Issue by regebro** [regebro/pyroma#2]
Thanks to Tarek I realized there are two more checks that should be done:

1. Tags should match other data, for example, if you have licence='MIT', the 'License :: OSI Approved :: MIT License' should also be included.
2. Requirements in setup.py and requirements.txt should match.

**Comment by The-Compiler** [comment]
Not so sure about 2. - for example, I have some optional dependencies, which I don't want to require in setup.py, but (for reproducability) have in requirements.txt.

Also see [setup.py vs. requirements.txt](https://caremad.io/posts/2013/07/setup-vs-requirement/).

**Comment by regebro** [comment]
You can specify optional dependencies in setup.py as well with [extras_require](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).

**Comment by 4383** [comment]
Hello!

How to obtain a correlation table of license field valid values by classifiers?
Full list of [valid classifiers is available](https://pypi.python.org/pypi?%3Aaction=list_classifiers), but I didn't found a list like this for license attribute.

I already can test if license classifier exist but I can't compare both...

**Comment by 4383** [comment]
#7 implement license exist in classifiers

**Comment by Kristinita** [comment]
+1 for classifiers validation. I don't find in PyPI Python module, that can check classifiers.

Thanks.

**Comment by regebro** [comment]
Creating a reliable mapping from what is in the license to what is in the classifiers isn't obvious, and will require a lot of manual maintenance, so I'm thinking of skipping it.

**Comment by regebro** [comment]
Implemented the classifier tests.
Requirements is a whole different batch of problems that I'm not ready to take on.
