### ISSUE TITLE
Accept alternate readthedocs.org domain names

### ISSUE THREAD

**Issue by paternal** [regebro/pyroma#3]
[According to your code](https://github.com/regebro/pyroma/blob/2035d4bb411236f09860166f91c0cee8e0489b42/pyroma/pypidata.py#L15), the only accepted domain name for documentation is http://readthedocs.org. However, other valid domain names are available (see the [readthedocs documentation](https://docs.readthedocs.io/en/latest/alternate_domains.html#rtfd-org)): http://rtfd.io, http://rtfd.org, http://readthedocs.io.

Shouldn't these be accepted as well?

Regards,
-- Louis

**Comment by regebro** [comment]
After considering this back and forth I decided I shouldn't recommend any places to host documentation.
