### ISSUE TITLE
Don't mark down when known Trove licence present +`license` omitted

### ISSUE THREAD

**Issue by hugovk** [regebro/pyroma#38]
According to https://packaging.python.org/guides/distributing-packages-using-setuptools/#license:

> The ``license`` argument doesn't have to indicate the license under
> which your package is being released, although you may optionally do
> so if you want.  If you're using a standard, well-known license, then
> your main indication can and should be via the ``classifiers``
> argument. Classifiers exist for all major open-source licenses.
> 
>  The "license" argument is more typically used to indicate differences
> from well-known licenses, or to include your own, unique license. As a
> general rule, it's a good idea to use a standard, well-known license,
> both to avoid confusion and because some organizations avoid software
> whose license is unapproved.

This was added in https://github.com/pypa/packaging.python.org/pull/492 to "indicate that this argument is meant for deviations from the Trove classifier, not instead of it".

# Actual result

If a project has a known Trove licence and the `license` classifier, it gets 10/10.

If the redundant `license` is removed, it's marked down to 9/10.

# Expected result

Instead, pyroma should give 10/10 if there's a known Trove licence and no `license` argument. It should be marked down if it has both.

If the Trove licence is something like `License :: Other/Proprietary License`, it should be 10/10 when there is a `license` explaining what is being used, and marked down when `license` is missing.

**Comment by regebro** [comment]
Fixed
