### ISSUE TITLE
Accept markdown long descriptions

### ISSUE THREAD

**Issue by JulienPalard** [regebro/pyroma#42]
If a setup configuration tells `long_description_content_type="text/markdown"`, then the long description should be checked for Markdown validity instead of ReST validity.

For example in pospell:
https://github.com/JulienPalard/pospell/blob/master/setup.py#L13

PyPI renders it correctly:
https://pypi.org/p/pospell

But pyroma whines:
```
pyroma .
------------------------------
Checking .
Found pospell
------------------------------
Your long_description is not valid ReST: 
<string>:41: (ERROR/3) Unexpected indentation.
<string>:39: (WARNING/2) Inline literal start-string without end-string.
<string>:52: (WARNING/2) Inline emphasis start-string without end-string.
<string>:55: (WARNING/2) Inline strong start-string without end-string.
<string>:55: (WARNING/2) Inline emphasis start-string without end-string.
<string>:57: (WARNING/2) Option list ends without a blank line; unexpected unindent.
<string>:59: (WARNING/2) Definition list ends without a blank line; unexpected unindent.
<string>:59: (WARNING/2) Inline literal start-string without end-string.
<string>:59: (WARNING/2) Inline interpreted text or phrase reference start-string without end-string.
------------------------------
Final rating: 9/10
Cottage Cheese
------------------------------
```

**Comment by regebro** [comment]
I can't find a way to syntax check markdown, so I will just skip any syntax check when the type is text/markdown or text/plain.

**Comment by jamadden** [comment]
> I can't find a way to syntax check markdown, so I will just skip any syntax check when the type is text/markdown 

Skipping a syntax check for markdown is what [twine does.](https://github.com/pypa/twine/pull/462#issuecomment-494084034)

**Comment by regebro** [comment]
Ah, good to know.

**Comment by cthoyt** [comment]
Is there a timeline for the 2.6 release?

**Comment by fniessink** [comment]
Version 2.6 was released a couple of days ago. I can confirm it solves this issue.
