### ISSUE TITLE
Suggestion: quiet output for providing just the score

### ISSUE THREAD

**Issue by Liam-Deacon** [regebro/pyroma#47]
Hello, I had an idea that some people may just want a single rating e.g. `9` (for 9/10) returned from the output if they are using this as part of a chain of tools - what do you think to creating a `--quiet` or similar option? (I'd be happy to help/raise a PR)

**Comment by regebro** [comment]
I'm not opposed to it.

**Comment by hugovk** [comment]
Please see PR https://github.com/regebro/pyroma/pull/60.
