### ISSUE TITLE
conda-forge link is broken

### ISSUE THREAD

**Issue by asears** [regebro/pyroma#63]
https://anaconda.org/conda-forge/pyroma the homepage points to an old bitbucket link.

**Comment by CAM-Gerlach** [comment]
FYI, the feedstock for the conda forge package is located at [conda-forge/pyroma-feedstock](https://github.com/conda-forge/pyroma-feedstock), and was apparently originally maintained by @jakirkham but hasn't been updated in a year. You can submit a PR there, though if it is no longer being maintained, you'll have to ask the conda-forge devs for maintainer access (assuming you don't mind doing so). Thanks!

**Comment by CAM-Gerlach** [comment]
FYI, I've just been added as a maintainer of the Pyroma Conda-Forge feedstock, and have opened conda-forge/pyroma-feedstock#16 to update Pyroma to a more recent version, in which I also updated the outdated URL.
