### ISSUE TITLE
Disable checks

### ISSUE THREAD

**Issue by kasium** [regebro/pyroma#69]
Hey,

I use `setuptools-scm` to generate the version of my project. This means, that the `setup` call has no `version?` argument. Therefore I can't achieve a full score with pyroma.

It would be cool to have a way to disable check by e.g. a CLI parameter and/or configuration file (`pyproject.toml`)

**Comment by regebro** [comment]
Supporting more modern PEP standards would be nice. Supporting setuptools-scm specifically isn't anything I'm going to spend time on. 

Don't worry about not having a perfect score. It's not a competition. The tool is there to give you hints of what could be improved.

**Comment by regebro** [comment]
Honestly, running it pre-commits doesn't make sense. Run it before release. If you use the excellent zest.releaser it will do it as a part of the release process.

**Comment by regebro** [comment]
On the other hand, I could probably implement a --success-level parameter.

**Comment by CAM-Gerlach** [comment]
(this was what I was imprecisely referring to with 

> This can be partially mitigated by manually configuring the hook invocation to use a lower fail threshold, but given the lack of precision, does run the risk of obscuring other issues.

BTW)

**Comment by regebro** [comment]
I see.
