### ISSUE TITLE
Pyroma reports 'Your package does not have author data' when author is in fact specified in pyproject.toml

### ISSUE THREAD

**Issue by bessman** [regebro/pyroma#77]
Per PEP621, author name and email should be specified in pyproject.toml as:
```
[project]
# ...
authors = [{name = "John Doe", email = "john@doe.com"}]
```
When this format is used, pyroma says 'Your package does not have author data.'

I suspect this is the reason:

> [1. If only name is provided, the value goes in Author/Maintainer as appropriate.
> 2. If only email is provided, the value goes in Author-email/Maintainer-email as appropriate.
> 3. If both email and name are provided, the value goes in Author-email/Maintainer-email as appropriate, with the format {name} <{email}> (with appropriate quoting, e.g. using email.headerregistry.Address).](https://peps.python.org/pep-0621/#authors-maintainers)

I.e. if both `name` and `email` are both provided, the Author/Maintainer field is left unpopulated.

**Comment by regebro** [comment]
IIRC reading metadata from pyproject.toml isn't supported yet.

**Comment by bessman** [comment]
The rest of the metadata gets read from the pyrproject.toml without issue. I tested the change suggested by @CAM-Gerlach and it seems to work.

**Comment by regebro** [comment]
OK, great! I remember I was waiting for a release of setuptools, I didn't expect it would just start working by itself, but it seems it did, then. 

> i.e. if both name and email are both provided, the Author/Maintainer field is left unpopulated.

How amazingly annoying. OK, will fix when I get time.
