### ISSUE TITLE
Parsing error `<string>:1: (WARNING/2) Inline strong start-string without end-string.`

### ISSUE THREAD

**Issue by Aluriak** [regebro/pyroma#9]
`setup.cfg`:

    [metadata]
    name = pp
    long_description = file: README.mkd

`README.mkd`:

    # title
    **a**bc **d**ef **h**ij.

Command: `pyroma .`

Output:

    Checking .
    Found pp
    <string>:1: (WARNING/2) Inline strong start-string without end-string.
    <string>:1: (WARNING/2) Inline strong start-string without end-string.
    <string>:1: (WARNING/2) Inline strong start-string without end-string.
    ------------------------------
    ... (normal pyroma output)

I searched this error on the web, it appears in many projects, probably du to the `**a**b` scheme, that would allow to give weight to only the first letter of the word `ab`, but is somehow not handled by some widely-used parser.
I did not found anything about that hypothetical parser.

**Comment by regebro** [comment]
Yes, that syntax is not valid ReStructuredText, which is the format used in this case.

Try this: `**a**\bc **d**\ef **h**\ij.`

**Comment by Aluriak** [comment]
Good to know, thank you for answering !
