### ISSUE TITLE
Upload wheel to PyPI

### ISSUE THREAD

**Issue by hugovk** [regebro/pyroma#91]
The new 4.1 release at https://pypi.org/project/pyroma/4.1/#files is missing a wheel. 

4.0 had one: https://pypi.org/project/pyroma/4.0/#files

The [recommended way](https://packaging.python.org/en/latest/flow/#the-built-distributions-wheels) is something like this:

```sh
git checkout 4.1
python -m pip install build
python -m build
```

Please could you upload a wheel? Thanks!

**Comment by regebro** [comment]
Done
